# -*- coding: utf-8 -*-
"""Streamlit AI Assistant App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FCQ6I4E0exthH-GDwhRDyReEWOaEHkwU
"""

import streamlit as st
import pandas as pd
import uuid
import os
import json
from typing import Dict, Any
from dotenv import load_dotenv
 
# Use matplotlib for plotting if available; avoid st.bar_chart which imports Altair
try:
    import matplotlib.pyplot as plt
    _HAS_MATPLOTLIB = True
except Exception:
    _HAS_MATPLOTLIB = False

# Load environment variables from .env file
load_dotenv()

# Verify API key is loaded
if not os.getenv("GEMINI_API_KEY"):
    st.error("GEMINI_API_KEY not found in environment variables. Please check your .env file.")
    st.stop()

# Import the backend functions from your modules
import sys
import os

# Add the parent directory to Python path so we can import from backend
backend_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(backend_dir)

try:
    from backend.code_generator_module import generate_code
    from backend.code_explainer_module import explain_code
    from backend.feedback_logger_module import log_feedback
    from backend.user_history_module import log_user_query
    from backend.admin_dashboard_module import get_dashboard_stats
    from backend.user_management_module import (
        register_user, register_user_with_password, set_password_for_user,
        verify_user_password, generate_password_reset_otp, reset_password_with_otp,
        get_all_users, get_user_by_id, get_user_by_username, get_user_activity,
        get_user_stats, replace_user, log_user_activity, delete_user
    )
except ImportError as e:
    st.error(f"Failed to import backend modules. Make sure all .py files are in the same directory. Error: {e}")
    st.stop()

# --- Page Configuration ---
st.set_page_config(
    page_title="CodeGenie AI",
    page_icon="🤖",
    layout="wide",
)

# --- Session State Initialization ---
# Initialize session state variables for authentication and app state
if 'is_authenticated' not in st.session_state:
    st.session_state.is_authenticated = False
if 'user_id' not in st.session_state:
    st.session_state.user_id = None
if 'username' not in st.session_state:
    st.session_state.username = None
if 'generated_code' not in st.session_state:
    st.session_state.generated_code = ""
if 'explanation' not in st.session_state:
    st.session_state.explanation = ""
if 'last_query' not in st.session_state:
    st.session_state.last_query = ""
if 'last_language' not in st.session_state:
    st.session_state.last_language = ""

# --- Authentication gate: require login/signup before using the app ---
if not st.session_state.get('is_authenticated', False):
    # Show ONLY login/signup page - NO SIDEBAR
    st.title("Welcome to CodeGenie — please sign in or register")
    auth_tabs = st.tabs(["Login", "Sign up", "Forgot Password"])

    with auth_tabs[0]:
        st.subheader("Login")
        with st.form("login_form"):
            identifier = st.text_input("User ID or Username")
            password = st.text_input("Password", type="password")
            if st.form_submit_button("Login"):
                if not identifier or not password:
                    st.warning("Please provide User ID/Username and password.")
                else:
                    res = verify_user_password(identifier, password)
                    if res.get('success'):
                        st.session_state.is_authenticated = True
                        st.session_state.user_id = res.get('user_id')
                        user = get_user_by_id(res.get('user_id'))
                        st.session_state.username = user.get('username') if user else None
                        try:
                            log_user_activity(st.session_state.user_id, 'login')
                        except Exception:
                            pass
                        st.success("Logged in successfully")
                        st.rerun()
                    else:
                        st.error(res.get('error', 'Login failed'))

    with auth_tabs[1]:
        st.subheader("Sign up")
        with st.form("signup_form"):
            new_user_id = st.text_input("User ID:")
            new_username = st.text_input("Username:")
            new_email = st.text_input("Email (optional):")
            new_password = st.text_input("Password:", type="password")
            confirm = st.text_input("Confirm Password:", type="password")
            if st.form_submit_button("Sign up"):
                if not new_user_id or not new_username or not new_password:
                    st.warning("Please provide User ID, Username and Password.")
                elif new_password != confirm:
                    st.warning("Passwords do not match.")
                else:
                    res = register_user_with_password(new_user_id, new_username, new_password, new_email)
                    if res.get('success'):
                        st.session_state.is_authenticated = True
                        st.session_state.user_id = new_user_id
                        st.session_state.username = new_username
                        try:
                            log_user_activity(new_user_id, 'login')
                        except Exception:
                            pass
                        st.success("Account created and logged in")
                        st.rerun()
                    else:
                        st.error(res.get('error', 'Signup failed'))

    with auth_tabs[2]:
        st.subheader("Forgot Password")
        with st.form("forgot_form"):
            fid = st.text_input("User ID or Username for password reset")
            if st.form_submit_button("Send OTP"):
                if not fid:
                    st.warning("Please provide User ID or Username.")
                else:
                    otp_res = generate_password_reset_otp(fid)
                    if otp_res.get('success'):
                        st.info("OTP generated. In development mode the OTP is displayed here; in production it would be emailed.")
                        st.write(f"OTP (dev): {otp_res.get('otp')} (expires {otp_res.get('expiry')})")
                    else:
                        st.error(otp_res.get('error', 'Could not generate OTP'))

        st.markdown("---")
        with st.form("forgot_reset_form"):
            fid2 = st.text_input("User ID or Username (again)")
            otp = st.text_input("OTP")
            new_pw = st.text_input("New password", type="password")
            new_pw_conf = st.text_input("Confirm new password", type="password")
            if st.form_submit_button("Reset Password"):
                if new_pw != new_pw_conf:
                    st.warning("Passwords do not match")
                else:
                    reset_res = reset_password_with_otp(fid2, otp, new_pw)
                    if reset_res.get('success'):
                        st.success("Password reset successful — you may now login")
                    else:
                        st.error(reset_res.get('error', 'Reset failed'))

    # Stop here until user authenticates
    st.stop()

# --- User is authenticated - now show sidebar with navigation ---
with st.sidebar:
    st.title("Navigation")

    def switch_page(new_page):
        st.session_state.page = new_page
        st.rerun()
    
    # Initialize page in session state if not exists
    if 'page' not in st.session_state:
        st.session_state.page = "CodeGenie"
    
    # Create bordered containers for each navigation option
    with st.container(border=True):
        st.write("### Navigate To")
        
        # CodeGenie Option
        with st.container(border=True):
            col1, col2 = st.columns([1, 4])
            with col1:
                st.write("🤖")
            with col2:
                if st.button("CodeGenie", use_container_width=True, key="nav_codegenie"):
                    switch_page("CodeGenie")
                    
        # Admin Dashboard Option
        with st.container(border=True):
            col1, col2 = st.columns([1, 4])
            with col1:
                st.write("📊")
            with col2:
                if st.button("Admin Dashboard", use_container_width=True, key="nav_admin"):
                    switch_page("AdminDashboard")
        
        # Code Explainer Option
        with st.container(border=True):
            col1, col2 = st.columns([1, 4])
            with col1:
                st.write("🔍")
            with col2:
                if st.button("Code Explainer", use_container_width=True, key="nav_code_explainer"):
                    switch_page("CodeExplainer")
    
    # --- Share URL Section ---
    with st.container(border=True):
        st.write("### 🔗 Share URL")
        
        # Get the app URL
        import socket
        try:
            # Get local IP address
            hostname = socket.gethostname()
            local_ip = socket.gethostbyname(hostname)
        except:
            local_ip = "localhost"
        
        # Streamlit default port
        streamlit_port = 8501
        
        # Local network URL
        local_url = f"http://{local_ip}:{streamlit_port}"
        
        st.write("**Local Network URL:**")
        st.code(local_url, language="text")
        
        # Button to copy to clipboard
        col1, col2 = st.columns(2)
        with col1:
            st.write(f"Share with friend on:")
            st.caption(f"IP: {local_ip}")
        with col2:
            st.info(f"Port: {streamlit_port}")
    
    # Refresh button with border
    with st.container(border=True):
        if st.button("🔄 Refresh View", use_container_width=True, key="nav_refresh"):
            st.rerun()
    
    # Logout button with border
    with st.container(border=True):
        if st.button("🚪 Logout", use_container_width=True, key="nav_logout", type="secondary"):
            st.session_state.is_authenticated = False
            st.session_state.user_id = None
            st.session_state.username = None
            try:
                log_user_activity(st.session_state.user_id, 'logout')
            except Exception:
                pass
            st.success("Logged out successfully!")
            st.rerun()

# Get current page from session state
page = st.session_state.page

# ======================================================================================
# --- Page 1: CodeGenie (Main Application) ---
# ======================================================================================
if st.session_state.page == "CodeGenie":
    st.title("🤖 CodeGenie AI Assistant")
    st.subheader("Your AI-powered partner for code generation and explanation.")

    # --- Code Generation Section ---
    with st.container(border=True):
        st.header("1. Generate Code")
        prompt = st.text_area("Enter your code prompt:", height=100, placeholder="e.g., A Python function to check for palindromes")
        language = st.selectbox(
            "Select language:",
            ["Python", "C++", "JavaScript", "SQL"]
        )

        if st.button("✨ Generate Code"):
            if not prompt:
                st.warning("Please enter a prompt.")
            else:
                with st.spinner("Generating code... Please wait."):
                    generated_code = generate_code(prompt, language)
                    st.session_state.generated_code = generated_code
                    st.session_state.last_query = prompt  # Save for logging
                    st.session_state.last_language = language # Save for logging
                    st.session_state.explanation = "" # Reset explanation

                    # Log the interaction immediately after generation so it is
                    # recorded even if the user doesn't click "Explain This Code".
                    try:
                        log_user_query(
                            user_id=st.session_state.user_id,
                            query=st.session_state.last_query,
                            language=st.session_state.last_language,
                            generated_code=st.session_state.generated_code,
                            explanation=st.session_state.explanation,
                        )
                    except Exception as e:
                        # Do not block the UI for logging errors; just show a warning
                        st.warning(f"Warning: failed to log query immediately: {e}")

                    # Treat only generation *errors* that start with the prefix "Error:" as errors.
                    # Some generated code may contain error messages inside strings (e.g. "Error: ...")
                    # which should not be treated as an overall generation failure.
                    if isinstance(generated_code, str) and generated_code.strip().startswith("Error:"):
                        st.error(generated_code)

    # --- Code Display and Explanation Section ---
    if st.session_state.generated_code and not (isinstance(st.session_state.generated_code, str) and st.session_state.generated_code.strip().startswith("Error:")):
        st.header("Generated Code")
        st.code(st.session_state.generated_code, language=st.session_state.last_language.lower())

        with st.container(border=True):
            st.header("2. Explain Code")
            style = st.selectbox(
                "Select explanation style:",
                ["Beginner-Friendly", "Technical Deep-Dive", "Step-by-Step Guide", "Real-World Examples", "Bullet Points"]
            )

            if st.button("🧠 Explain This Code"):
                with st.spinner(f"Generating {style} explanation..."):
                    code_to_explain = st.session_state.generated_code
                    explanation = explain_code(code_to_explain, style)
                    st.session_state.explanation = explanation

                    # Log the complete interaction
                    try:
                        log_user_query(
                            user_id=st.session_state.user_id,
                            query=st.session_state.last_query,
                            language=st.session_state.last_language,
                            generated_code=code_to_explain,
                            explanation=explanation
                        )
                        st.toast("Interaction logged to history.")
                    except Exception as e:
                        st.error(f"Failed to log user history: {e}")

        # Display explanation if it exists
        if st.session_state.explanation:
            st.markdown(st.session_state.explanation)

        # --- Feedback Section ---
        with st.container(border=True):
            st.header("3. Provide Feedback")
            st.write("How satisfied are you with the *generated code*?")

            # Use columns for a cleaner layout
            col1, col2 = st.columns([1, 2])
            with col1:
                rating = st.slider("Rating (1=Bad, 5=Good):", 1, 5, 3)
            with col2:
                comments = st.text_input("Optional comments:", placeholder="e.g., It missed an edge case...")

            if st.button("Submit Feedback"):
                try:
                    log_feedback(
                        user_id=st.session_state.user_id,
                        query=st.session_state.last_query,
                        rating=rating,
                        comments=comments
                    )
                    st.success("Thank you! Your feedback has been logged.")
                except Exception as e:
                    st.error(f"Failed to log feedback: {e}")

# ======================================================================================
# --- Page 2: Admin Dashboard ---
# ======================================================================================
elif st.session_state.page == "CodeExplainer":
    st.title("🔍 Code Explainer")
    st.subheader("Paste your code here and get a detailed explanation")

    # --- Code Input Section ---
    with st.container(border=True):
        st.header("1. Paste Code")
        code_to_explain = st.text_area("Enter your code:", height=150, placeholder="e.g., def is_palindrome(s):\n    return s == s[::-1]")
        
        language = st.selectbox(
            "Select programming language:",
            ["Python", "C++", "JavaScript", "SQL", "Other"]
        )

    # --- Explanation Section ---
    if code_to_explain and code_to_explain.strip():
        with st.container(border=True):
            st.header("2. Explanation Style")
            style = st.selectbox(
                "Select explanation style:",
                ["Beginner-Friendly", "Technical Deep-Dive", "Step-by-Step Guide", "Real-World Examples", "Bullet Points"],
                key="explainer_style"
            )

            if st.button("🧠 Explain Code"):
                with st.spinner("Generating explanation..."):
                    try:
                        explanation = explain_code(code_to_explain, style)
                        st.session_state.explanation_result = explanation
                        st.session_state.last_explained_code = code_to_explain
                        st.session_state.last_explained_language = language

                        # Log the explanation interaction
                        try:
                            log_user_query(
                                user_id=st.session_state.user_id,
                                query=None,
                                language=language,
                                generated_code=code_to_explain,
                                explanation=explanation
                            )
                        except Exception as e:
                            st.warning(f"Note: Could not log to history: {e}")
                    except Exception as e:
                        st.error(f"Failed to generate explanation: {e}")

        # --- Display Explanation ---
        if hasattr(st.session_state, 'explanation_result') and st.session_state.explanation_result:
            st.markdown(st.session_state.explanation_result)

            # --- Feedback Section ---
            with st.container(border=True):
                st.header("3. Provide Feedback")
                st.write("How helpful was this explanation?")

                col1, col2 = st.columns([1, 2])
                with col1:
                    rating = st.slider("Rating (1=Not Helpful, 5=Very Helpful):", 1, 5, 3, key="explainer_rating")
                with col2:
                    comments = st.text_input("Optional comments:", placeholder="e.g., Could be clearer on the logic...", key="explainer_comments")

                if st.button("Submit Feedback", key="submit_explainer_feedback"):
                    try:
                        log_feedback(
                            user_id=st.session_state.user_id,
                            query=st.session_state.last_explained_code[:100] if hasattr(st.session_state, 'last_explained_code') else "Code snippet",
                            rating=rating,
                            comments=comments
                        )
                        st.success("Thank you! Your feedback has been logged.")
                    except Exception as e:
                        st.error(f"Failed to log feedback: {e}")
    else:
        st.info("👆 Paste some code above to get started!")

elif st.session_state.page == "AdminDashboard":
    st.title("📊 Admin Dashboard")
    st.subheader("Comprehensive admin panel for monitoring and management.")

    # Initialize admin_dashboard_page if not exists
    if 'admin_dashboard_page' not in st.session_state:
        st.session_state.admin_dashboard_page = "Overview"
    
    # --- Admin Dashboard Navigation ---
    st.markdown("---")
    col1, col2, col3, col4, col5, col6, col7 = st.columns(7)
    
    with col1:
        if st.button("� Overview", use_container_width=True, key="admin_overview"):
            st.session_state.admin_dashboard_page = "Overview"
            st.rerun()
    
    with col2:
        if st.button("⭐ Feedback", use_container_width=True, key="admin_feedback"):
            st.session_state.admin_dashboard_page = "Feedback"
            st.rerun()
    
    with col3:
        if st.button("📊 Queries", use_container_width=True, key="admin_queries"):
            st.session_state.admin_dashboard_page = "Queries"
            st.rerun()
    
    with col4:
        if st.button("💻 Languages", use_container_width=True, key="admin_languages"):
            st.session_state.admin_dashboard_page = "Languages"
            st.rerun()
    
    with col5:
        if st.button("✅ Code Quality", use_container_width=True, key="admin_quality"):
            st.session_state.admin_dashboard_page = "CodeQuality"
            st.rerun()
    
    with col6:
        if st.button("👥 Members", use_container_width=True, key="admin_members"):
            st.session_state.admin_dashboard_page = "Members"
            st.rerun()
    
    with col7:
        if st.button("🔄 Refresh", use_container_width=True, key="admin_refresh"):
            try:
                st.cache_data.clear()
            except Exception:
                pass
            st.rerun()
    
    st.markdown("---")

    # Load dashboard stats
    try:
        stats = get_dashboard_stats()
    except Exception as e:
        import logging
        logging.exception("Error while computing dashboard stats")
        st.warning("Could not compute dashboard stats; showing fallback values.")
        stats = {
            "average_rating": 0.0,
            "total_feedback": 0,
            "top_queries": {},
            "language_stats": {},
            "total_queries": 0,
            "code_quality": None
        }

    # --- PAGE 1: OVERVIEW METRICS ---
    if st.session_state.admin_dashboard_page == "Overview":
        st.header("📈 Overview Metrics")
        with st.container(border=True):
            col1, col2, col3, col4 = st.columns(4)
            col1.metric("Total Queries", stats.get('total_queries', 0))
            col2.metric("Total Feedback", stats.get('total_feedback', 0))
            col3.metric("Avg Rating", f"{stats.get('average_rating', 0.0):.2f}/5.0")
            col4.metric("Active Users", len(get_all_users()))

    # --- PAGE 2: RATINGS & FEEDBACK ---
    elif st.session_state.admin_dashboard_page == "Feedback":
        st.header("⭐ Ratings & Feedback")
        
        feedback_tabs = st.tabs(["Rating Overview", "Feedback Details"])
        
        with feedback_tabs[0]:
            col1, col2 = st.columns(2)
            with col1:
                st.metric("Average Rating", f"{stats.get('average_rating', 0.0):.2f} / 5.0")
                st.metric("Total Feedback Entries", stats.get('total_feedback', 0))
            
            with col2:
                # Rating distribution chart
                try:
                    from backend.feedback_logger_module import FEEDBACK_FILE
                    import json
                    if os.path.exists(FEEDBACK_FILE):
                        with open(FEEDBACK_FILE, 'r', encoding='utf-8') as f:
                            try:
                                data = json.load(f)
                            except Exception:
                                data = []
                    else:
                        data = []

                    if isinstance(data, list) and data:
                        feedback_df = pd.DataFrame.from_records(data)
                    else:
                        feedback_df = pd.DataFrame()

                    if not feedback_df.empty and 'rating' in feedback_df.columns:
                        rating_counts = feedback_df['rating'].value_counts().sort_index()
                        st.write("**Rating Distribution:**")
                        if _HAS_MATPLOTLIB:
                            try:
                                fig, ax = plt.subplots(figsize=(5, 3))
                                rating_counts.sort_index().plot(kind='bar', ax=ax, color='gold')
                                ax.set_xlabel('Rating')
                                ax.set_ylabel('Count')
                                ax.set_title('Rating Distribution')
                                plt.tight_layout()
                                st.pyplot(fig)
                            except Exception as e:
                                st.error(f"Could not render rating chart: {e}")
                        else:
                            st.table(rating_counts)
                    else:
                        st.info("No rating distribution data available.")
                except Exception as e:
                    st.info(f"No rating distribution data available. {e}")
        
        with feedback_tabs[1]:
            try:
                from backend.feedback_logger_module import FEEDBACK_FILE
                feedback_df = pd.read_json(FEEDBACK_FILE)
                if not feedback_df.empty:
                    feedback_df['timestamp'] = pd.to_datetime(feedback_df['timestamp'])
                    feedback_df = feedback_df.sort_values('timestamp', ascending=False)
                    
                    display_cols = ['timestamp', 'user_id', 'rating', 'comments', 'query']
                    st.dataframe(
                        feedback_df[display_cols].head(20),
                        use_container_width=True
                    )
                else:
                    st.info("No feedback data available.")
            except Exception as e:
                st.warning(f"Could not load feedback data: {e}")

    # --- PAGE 3: QUERIES & CHARTS ---
    elif st.session_state.admin_dashboard_page == "Queries":
        st.header("📊 Queries & Charts")
        
        queries_tabs = st.tabs(["Top Queries", "Trends"])
        
        with queries_tabs[0]:
            st.subheader("Top 5 Trending Queries")
            top_queries = stats.get('top_queries', {})
            if top_queries:
                df_queries = pd.DataFrame(list(top_queries.items()), columns=['Query', 'Count'])
                col1, col2 = st.columns(2)
                with col1:
                    st.dataframe(df_queries, use_container_width=True, hide_index=True)
                with col2:
                    if _HAS_MATPLOTLIB:
                        try:
                            fig, ax = plt.subplots(figsize=(8, 5))
                            df_queries.set_index('Query')['Count'].plot(kind='barh', ax=ax, color='steelblue')
                            ax.set_xlabel('Count')
                            ax.set_title('Query Frequency')
                            plt.tight_layout()
                            st.pyplot(fig)
                        except Exception as e:
                            st.error(f"Could not render chart: {e}")
                    else:
                        st.info("Install matplotlib to see chart")
            else:
                st.info("No query data available.")
        
        with queries_tabs[1]:
            st.subheader("Query Timeline")
            try:
                from backend.user_history_module import HISTORY_FILE
                if os.path.exists(HISTORY_FILE):
                    with open(HISTORY_FILE, 'r', encoding='utf-8') as f:
                        try:
                            data = json.load(f)
                        except json.JSONDecodeError:
                            data = []
                else:
                    data = []
                
                if isinstance(data, list) and data:
                    history_df = pd.DataFrame.from_records(data)
                else:
                    history_df = pd.DataFrame()

                if not history_df.empty and 'timestamp' in history_df.columns:
                    history_df['timestamp'] = pd.to_datetime(history_df['timestamp'], errors='coerce')
                    history_df['date'] = history_df['timestamp'].dt.date
                    queries_per_day = history_df.groupby('date').size()
                    
                    if _HAS_MATPLOTLIB and not queries_per_day.empty:
                        try:
                            fig, ax = plt.subplots(figsize=(10, 5))
                            queries_per_day.plot(kind='line', ax=ax, color='steelblue', marker='o')
                            ax.set_xlabel('Date')
                            ax.set_ylabel('Queries')
                            ax.set_title('Query Timeline')
                            plt.xticks(rotation=45)
                            plt.tight_layout()
                            st.pyplot(fig)
                        except Exception as chart_err:
                            st.warning(f"Could not render timeline chart: {chart_err}")
                            st.table(queries_per_day)
                    else:
                        st.table(queries_per_day)
                else:
                    st.info("No timeline data available.")
            except Exception as e:
                st.warning(f"Could not load timeline data: {e}")

    # --- PAGE 4: LANGUAGE USAGE ---
    elif st.session_state.admin_dashboard_page == "Languages":
        st.header("💻 Language Usage")
        
        lang_tabs = st.tabs(["Statistics", "Breakdown"])
        
        with lang_tabs[0]:
            lang_stats = stats.get('language_stats', {})
            if lang_stats:
                df_lang = pd.DataFrame(list(lang_stats.items()), columns=['Language', 'Count'])
                st.dataframe(df_lang, use_container_width=True, hide_index=True)
            else:
                st.info("No language usage data available.")
        
        with lang_tabs[1]:
            lang_stats = stats.get('language_stats', {})
            if lang_stats:
                df_lang = pd.DataFrame(list(lang_stats.items()), columns=['Language', 'Count'])
                
                if _HAS_MATPLOTLIB:
                    try:
                        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
                        
                        df_lang.set_index('Language').plot(kind='bar', legend=False, ax=ax1)
                        ax1.set_ylabel('Count')
                        ax1.set_title('Language Distribution (Bar)')
                        ax1.tick_params(axis='x', rotation=45)
                        
                        df_lang.plot(kind='pie', y='Count', labels=df_lang['Language'], 
                                   autopct='%1.1f%%', ax=ax2, legend=False)
                        ax2.set_title('Language Distribution (Pie)')
                        
                        plt.tight_layout()
                        st.pyplot(fig)
                    except Exception as e:
                        st.error(f"Failed to render charts: {e}")
                else:
                    st.info("Install matplotlib to see charts.")
            else:
                st.info("No language usage data available.")

    # --- PAGE 5: CODE QUALITY ---
    elif st.session_state.admin_dashboard_page == "CodeQuality":
        st.header("✅ Code Quality Metrics")
        
        cq = stats.get('code_quality', None)
        if cq:
            quality_tabs = st.tabs(["Summary", "Details"])
            
            with quality_tabs[0]:
                col1, col2, col3 = st.columns(3)
                with col1:
                    st.metric("Execution Success", f"{cq.get('execution_success_pct', 0.0):.2f}%")
                with col2:
                    syntax = cq.get('syntax', {})
                    pct_ok = syntax.get('pct_ok', 0.0)
                    st.metric("Python Syntax OK", f"{pct_ok:.2f}%")
                with col3:
                    runtime = cq.get('runtime', {'Good': 0, 'Average': 0, 'Poor': 0})
                    total_runtime = sum(runtime.values())
                    st.metric("Code Samples", f"{total_runtime}")
            
            with quality_tabs[1]:
                if _HAS_MATPLOTLIB:
                    col1, col2 = st.columns(2)
                    
                    with col1:
                        runtime = cq.get('runtime', {'Good': 0, 'Average': 0, 'Poor': 0})
                        df_runtime = pd.DataFrame(list(runtime.items()), columns=['Category', 'Count'])
                        st.subheader("Runtime Performance")
                        fig, ax = plt.subplots(figsize=(8, 5))
                        df_runtime.set_index('Category').plot(kind='bar', legend=False, ax=ax, color=['#2ca02c', '#ff7f0e', '#d62728'])
                        ax.set_ylabel('Count')
                        ax.set_title('Runtime Distribution')
                        ax.tick_params(axis='x', rotation=45)
                        plt.tight_layout()
                        st.pyplot(fig)
                    
                    with col2:
                        syntax = cq.get('syntax', {})
                        py_checked = syntax.get('python_checked', 0)
                        py_ok = syntax.get('python_syntax_ok', 0)
                        py_not_ok = max(0, py_checked - py_ok)
                        df_syntax = pd.DataFrame({
                            'Category': ['OK', 'Syntax Error'],
                            'Count': [py_ok, py_not_ok]
                        })
                        st.subheader("Python Syntax Check")
                        fig, ax = plt.subplots(figsize=(8, 5))
                        df_syntax.set_index('Category').plot(kind='bar', legend=False, ax=ax, color=['#2ca02c', '#d62728'])
                        ax.set_ylabel('Count')
                        ax.set_title('Syntax Breakdown')
                        ax.tick_params(axis='x', rotation=45)
                        plt.tight_layout()
                        st.pyplot(fig)
        else:
            st.info("Code quality data not available.")

    # --- PAGE 6: MEMBER MANAGEMENT ---
    elif st.session_state.admin_dashboard_page == "Members":
        st.header("👥 Member Management & History")
        
        if 'admin_unlocked' not in st.session_state:
            st.session_state.admin_unlocked = False

        if not st.session_state.admin_unlocked:
            pwd = st.text_input("Enter admin password to access Member Management:", type='password')
            if st.button("Unlock Member Management"):
                if pwd == "Password_123":
                    st.session_state.admin_unlocked = True
                    st.success("Admin access granted")
                else:
                    st.error("Incorrect admin password")

            st.info("This section is admin-only. Enter the admin password to view member management and history.")
        else:
            member_tabs = st.tabs(["All Members", "User Activity", "Member Operations"])

            with member_tabs[0]:
                st.subheader("Registered Members")
                users = get_all_users()
                if users:
                    users_data = []
                    for user in users:
                        stats_u = get_user_stats(user['user_id'])
                        users_data.append({
                            'User ID': user['user_id'],
                            'Username': user['username'],
                            'Email': user.get('email', 'N/A'),
                            'Logins': user.get('total_logins', 0),
                            'Queries': stats_u.get('activities', {}).get('queries', 0),
                            'Avg Rating': f"{stats_u.get('average_rating', 0.0):.2f}",
                            'Last Login': user.get('last_login', 'N/A')[:10]
                        })
                    df_users = pd.DataFrame(users_data)
                    st.dataframe(df_users, use_container_width=True, hide_index=True)
                else:
                    st.info("No registered members yet.")

            with member_tabs[1]:
                st.subheader("User Activity & History")
                users = get_all_users()
                if users:
                    user_options = {u['username']: u['user_id'] for u in users}
                    selected_user_name = st.selectbox("Select User to View:", list(user_options.keys()), key="user_select")
                    selected_user_id = user_options[selected_user_name]

                    user_stats = get_user_stats(selected_user_id)

                    col1, col2, col3 = st.columns(3)
                    col1.metric("Total Queries", user_stats.get('total_queries', 0))
                    col2.metric("Total Feedback", user_stats.get('total_feedback', 0))
                    col3.metric("Avg Rating", f"{user_stats.get('average_rating', 0.0):.2f}")

                    st.write("**Recent Activities:**")
                    activities = get_user_activity(selected_user_id)
                    if activities:
                        activity_df = pd.DataFrame(activities)
                        activity_df['timestamp'] = pd.to_datetime(activity_df['timestamp'])
                        activity_df = activity_df.sort_values('timestamp', ascending=False)

                        display_cols = ['timestamp', 'activity_type', 'query', 'language', 'rating', 'comments']
                        available_cols = [c for c in display_cols if c in activity_df.columns]

                        st.dataframe(
                            activity_df[available_cols].head(20),
                            use_container_width=True
                        )
                    else:
                        st.info("No activities recorded for this user.")
                else:
                    st.info("No users registered yet.")

            with member_tabs[2]:
                st.subheader("Member Operations")
                operation = st.radio("Select Operation:", ["Add Member", "Delete Member"], horizontal=True)

                if operation == "Add Member":
                    st.write("**Register New Member**")
                    with st.form("add_member_form"):
                        new_user_id = st.text_input("User ID:", placeholder="e.g., user_123")
                        new_username = st.text_input("Username:", placeholder="e.g., John Doe")
                        new_email = st.text_input("Email:", placeholder="e.g., john@example.com")
                        
                        if st.form_submit_button("✅ Register Member"):
                            if new_user_id and new_username:
                                result = register_user(new_user_id, new_username, new_email)
                                if result.get('success'):
                                    st.success(f"✅ Member '{new_username}' registered successfully!")
                                    st.rerun()
                                else:
                                    st.error(f"❌ Failed: {result.get('error', 'Unknown error')}")
                            else:
                                st.warning("Please fill in User ID and Username.")

                elif operation == "Delete Member":
                    st.write("**Delete Member**")
                    users = get_all_users()
                    if users:
                        user_options = {u['username']: u['user_id'] for u in users}
                        user_to_delete_name = st.selectbox("Select Member to Delete:", list(user_options.keys()), key="delete_user_select")
                        user_to_delete_id = user_options[user_to_delete_name]

                        st.warning(f"⚠️ You are about to delete '{user_to_delete_name}' and all their data. This action cannot be undone.")

                        if st.button("🗑️ Confirm Delete", type="secondary"):
                            result = delete_user(user_to_delete_id)
                            if result.get('success'):
                                st.success(f"✅ Member '{user_to_delete_name}' deleted successfully!")
                                st.rerun()
                            else:
                                st.error(f"❌ Failed: {result.get('error', 'Unknown error')}")
                    else:
                        st.info("No members to delete.")