# -*- coding: utf-8 -*-
"""Code Generator Module

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ou25sl5bwzD-blR4Ep6D9a4G_uXH6CGv
"""

import os
import requests
import logging
from typing import Optional
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Load API key from environment variables
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
API_URL = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key={GEMINI_API_KEY}"

def generate_code(prompt: str, language: str) -> str:
    """
    Generates code using the Gemini API based on a prompt and language.

    Args:
        prompt: The user's request (e.g., "create a fibonacci function").
        language: The target programming language (e.g., "Python", "JavaScript").

    Returns:
        A string containing the generated code, or an error message.
    """
    if not GEMINI_API_KEY:
        logger.error("GEMINI_API_KEY not set in environment variables.")
        return "Error: API key not configured."

    # System instruction to force the model to *only* return code
    # Language-specific prompts to generate better code
    language_prompts = {
        "Python": (
            "You are an expert Python developer. Generate clean, Pythonic code following PEP 8 "
            "standards. Include docstrings and type hints where appropriate. Focus on readability "
            "and modern Python features."
        ),
        "C++": (
            "You are an expert C++ developer. Generate modern C++ code (C++17 or later) with proper "
            "memory management. Use STL where appropriate. Consider efficiency and type safety."
        ),
        "JavaScript": (
            "You are an expert JavaScript developer. Generate modern JavaScript code (ES6+) with "
            "proper error handling. Use modern features like async/await, destructuring, and arrow "
            "functions where appropriate."
        ),
        "SQL": (
            "You are an expert SQL developer. Generate optimized SQL queries following best "
            "practices. Consider indexing and performance. Use appropriate JOIN types and "
            "subqueries where needed."
        )
    }

    # Get language-specific prompt or use default
    lang_prompt = language_prompts.get(
        language,
        f"You are an expert {language} developer. Generate clean, efficient code."
    )

    system_prompt = (
        f"{lang_prompt} Respond *only* with the raw code. Do not include markdown "
        "formatting (like ```language ... ```), explanations, or any other text. "
        "Just the code."
    )

    user_query = f"Generate a {language} code snippet for the following prompt: {prompt}"

    payload = {
        "contents": [{"parts": [{"text": user_query}]}],
        "systemInstruction": {
            "parts": [{"text": system_prompt}]
        },
    }

    headers = {'Content-Type': 'application/json'}

    try:
        response = requests.post(API_URL, headers=headers, json=payload, timeout=30)
        response.raise_for_status()  # Raise HTTPError for bad responses (4xx or 5xx)

        result = response.json()

        # Extract the text from the response
        if (
            "candidates" in result
            and result["candidates"]
            and "content" in result["candidates"][0]
            and "parts" in result["candidates"][0]["content"]
            and result["candidates"][0]["content"]["parts"]
        ):
            code_snippet = result["candidates"][0]["content"]["parts"][0]["text"]
            return code_snippet.strip()
        else:
            logger.warning(f"Unexpected API response structure: {result}")
            return f"Error: Could not parse response from model. Response: {result}"

    except requests.exceptions.HTTPError as http_err:
        logger.error(f"HTTP error occurred: {http_err} - Response: {response.text}")
        return f"Error: A server-side error occurred. Status code: {response.status_code}"
    except requests.exceptions.RequestException as req_err:
        logger.error(f"Error during API request: {req_err}")
        return "Error: Could not connect to code generation service."
    except (KeyError, IndexError, TypeError) as parse_err:
        logger.error(f"Error parsing API response: {parse_err} - Response: {result}")
        return "Error: Invalid response from code generation service."
    except Exception as e:
        logger.error(f"An unexpected error occurred in generate_code: {e}")
        return "Error: An unexpected error occurred."

if __name__ == "__main__":
    # Example usage (requires GEMINI_API_KEY to be set in env)
    if GEMINI_API_KEY:
        print("--- Testing Code Generator ---")
        py_prompt = "a function that returns the sum of two numbers"
        js_prompt = "a console.log statement that says 'Hello World'"

        print(f"Python Prompt: {py_prompt}")
        print(generate_code(py_prompt, "Python"))

        print(f"\nJavaScript Prompt: {js_prompt}")
        print(generate_code(js_prompt, "JavaScript"))
    else:
        print("Set GEMINI_API_KEY environment variable to run tests.")