# -*- coding: utf-8 -*-
"""Code Explainer Module

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1liOcPGiuYf3Abad8cp5CRJckLraO83_E
"""

import os
import requests
import logging
from typing import Optional

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Load API key from environment variables
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
API_URL = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key={GEMINI_API_KEY}"

def explain_code(code_snippet: str, style: str) -> str:
    """
    Explains a code snippet using the Gemini API in a specific style.

    Args:
        code_snippet: The string of code to explain.
        style: The desired explanation style (e.g., "beginner-friendly",
               "technical deep-dive", "in Hindi").

    Returns:
        A string containing the explanation, or a fallback message.
    """
    fallback_explanation = "Sorry, I couldn't generate an explanation at this time. Please try again."

    if not GEMINI_API_KEY:
        logger.error("GEMINI_API_KEY not set in environment variables.")
        return "Error: API key not configured."

    if not code_snippet.strip():
        return "No code provided to explain."

    system_prompt = (
        "You are an expert code explainer. You will be given a code snippet "
        "and an explanation style. Your task is to explain the code clearly "
        "and accurately in that specific style. Use markdown for formatting."
    )

    # Define style-specific prompts
    style_prompts = {
        "Beginner-Friendly": (
            "Explain this code for someone new to programming. Use simple terms, "
            "avoid jargon, and focus on the basic concepts."
        ),
        "Technical Deep-Dive": (
            "Provide a detailed technical analysis of this code, including design patterns, "
            "performance considerations, and best practices. Include technical terminology "
            "and explain complex concepts thoroughly."
        ),
        "Step-by-Step Guide": (
            "Break down this code into clear, logical steps. For each step, explain: "
            "1) What that line or block does, 2) Why it's necessary, and 3) How it "
            "contributes to the overall functionality."
        ),
        "Real-World Examples": (
            "Explain this code using real-world analogies and practical examples. "
            "Show how this code might be used in actual applications and provide "
            "concrete scenarios where this code would be useful."
        ),
        "Bullet Points": (
            "Break down this code into a clear, bulleted list of key points. "
            "For each major concept or section: • What it does • Why it's important "
            "• Key technical details • Best practices • Potential pitfalls"
        )
    }

    # Get the appropriate prompt for the selected style
    style_prompt = style_prompts.get(
        style,
        "Explain this code in a clear and understandable way."  # default prompt
    )

    user_query = (
        f"{style_prompt}\n\n"
        f"Code to explain:\n```\n{code_snippet}\n```"
    )

    payload = {
        "contents": [{"parts": [{"text": user_query}]}],
        "systemInstruction": {
            "parts": [{"text": system_prompt}]
        },
    }

    headers = {'Content-Type': 'application/json'}

    try:
        response = requests.post(API_URL, headers=headers, json=payload, timeout=30)
        response.raise_for_status()

        result = response.json()

        if (
            "candidates" in result
            and result["candidates"]
            and "content" in result["candidates"][0]
            and "parts" in result["candidates"][0]["content"]
            and result["candidates"][0]["content"]["parts"]
        ):
            explanation = result["candidates"][0]["content"]["parts"][0]["text"]
            return explanation.strip()
        else:
            logger.warning(f"Unexpected API response structure: {result}")
            return fallback_explanation

    except requests.exceptions.HTTPError as http_err:
        logger.error(f"HTTP error occurred: {http_err} - Response: {response.text}")
        return fallback_explanation
    except requests.exceptions.RequestException as req_err:
        logger.error(f"Error during API request: {req_err}")
        return fallback_explanation
    except (KeyError, IndexError, TypeError) as parse_err:
        logger.error(f"Error parsing API response: {parse_err} - Response: {result}")
        return fallback_explanation
    except Exception as e:
        logger.error(f"An unexpected error occurred in explain_code: {e}")
        return fallback_explanation

if __name__ == "__main__":
    # Example usage (requires GEMINI_API_KEY to be set in env)
    if GEMINI_API_KEY:
        print("--- Testing Code Explainer ---")
        test_code = "def add(a, b):\n    return a + b"

        print(f"Code:\n{test_code}\n")

        print("--- Beginner Style ---")
        print(explain_code(test_code, "beginner-friendly"))

        print("\n--- Technical Style ---")
        print(explain_code(test_code, "technical deep-dive"))

        print("\n--- Hindi Style ---")
        print(explain_code(test_code, "like I'm a 5-year-old in Hindi"))
    else:
        print("Set GEMINI_API_KEY environment variable to run tests.")