# -*- coding: utf-8 -*-
"""User History Module

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1neAVwLZyQSzism0I2QM8CAD0u8LlYV1J
"""

import json
import os
import logging
import threading
from datetime import datetime
from typing import Optional

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Resolve to the project's streamlit_app folder so logs are stored in the same place the UI reads from.
CURRENT_FILE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(CURRENT_FILE_DIR, '..'))
STREAMLIT_APP_DIR = os.path.join(PROJECT_ROOT, 'streamlit_app')
HISTORY_FILE = os.path.join(STREAMLIT_APP_DIR, 'user_history.json')
# Use a lock for thread-safe file writing
file_lock = threading.Lock()

def log_user_query(user_id: str, query: str, language: str, generated_code: str, explanation: str) -> None:
    """
    Logs a user's interaction (query, code, explanation) to a JSON file and user activity.

    Args:
        user_id: A unique identifier for the user.
        query: The user's original text prompt.
        language: The language selected for generation.
        generated_code: The code snippet produced by the model.
        explanation: The explanation produced for the code.
    """
    history_entry = {
        'timestamp': datetime.now().isoformat(),
        'user_id': user_id,
        'query': query,
        'language': language,
        'generated_code': generated_code,
        'explanation': explanation
    }

    with file_lock:
        try:
            # Try to read existing data
            if os.path.exists(HISTORY_FILE):
                with open(HISTORY_FILE, 'r', encoding='utf-8') as f:
                    try:
                        data = json.load(f)
                        if not isinstance(data, list):
                            data = []
                    except json.JSONDecodeError:
                        data = []
            else:
                data = []

            # Append new entry
            data.append(history_entry)

            # Write data back
            # Ensure directory exists
            os.makedirs(os.path.dirname(HISTORY_FILE), exist_ok=True)
            with open(HISTORY_FILE, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=4)
            logger.info(f"Successfully logged history for user {user_id}")
            
            # Also log to user activity if the module is available
            try:
                import sys
                import os as os_module
                backend_dir = os_module.path.abspath(os_module.path.join(os_module.path.dirname(__file__), '..'))
                if backend_dir not in sys.path:
                    sys.path.append(backend_dir)
                
                from backend.user_management_module import log_user_activity
                log_user_activity(
                    user_id=user_id,
                    activity_type='query',
                    query=query,
                    language=language
                )
            except Exception as e:
                logger.warning(f"Could not log to user activity: {e}")

        except (IOError, OSError) as e:
            logger.error(f"Failed to write to {HISTORY_FILE}: {e}")
        except Exception as e:
            logger.error(f"An unexpected error occurred in log_user_query: {e}")

if __name__ == "__main__":
    # Example usage
    print("--- Testing User History Logger ---")
    log_user_query(
        user_id="user_123",
        query="create a login button in html",
        language="HTML",
        generated_code="<button>Login</button>",
        explanation="This is a simple button."
    )
    log_user_query(
        user_id="user_123",
        query="fibonacci in python",
        language="Python",
        generated_code="def fib(n): ...",
        explanation="This is a fibonacci function."
    )
    print(f"Check {HISTORY_FILE} for output.")